baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Submariner k8s project documentation website"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/submariner-io/website/edit/master/src/content/"
  description = "Documentation website for the submariner project"
  author = "The submariner community"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Submariner k8s project documentation website"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/submariner-io/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Youtube demos"
url = "https://www.youtube.com/channel/UCZ3brSgl2v4boglZoeChClQ/videos"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Twitter"
identifier = "twitter"
url = "https://twitter.com/submarinerio"
weight = 20

[Languages.es]
title = "Proyecto Submariner, documentación"
weight = 2
languageName = "Spanish"

[[Languages.es.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
identifier = "ds"
url = "https://github.com/submariner-io/"
weight = 10

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Demos youtube"
url = "https://www.youtube.com/channel/UCZ3brSgl2v4boglZoeChClQ/videos"
weight = 11

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Twitter"
identifier = "twitter"
url = "https://twitter.com/submarinerio"
weight = 20

