name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Create deploy key to push	
      run: |	
        echo '=================== Create deploy key to push ==================='	
        set -x	
        mkdir $HOME/.ssh	
        ssh-keyscan -t rsa github.com > $HOME/.ssh/known_hosts
        echo "${GIT_DEPLOY_KEY}" > $HOME/.ssh/id_rsa
        chmod 400 $HOME/.ssh/id_rsa	
      env:	
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}	

    - name: Make the static files
      run: make static
  
    - name: Deploy
      run: ./scripts/publish
